"""Git integration para auto-commit."""

import subprocess
from pathlib import Path
from typing import Dict, Any


class GitManager:
    """Gestiona repositorios Git."""
    
    def __init__(self, workspace_dir: str = "aether_workspace"):
        self.workspace_dir = Path(workspace_dir)
    
    def init_repo(self, project_id: str, project_name: str) -> Dict[str, Any]:
        """Inicializar repositorio Git."""
        project_dir = self.workspace_dir / project_id
        
        try:
            # Init git
            subprocess.run(["git", "init"], cwd=str(project_dir), capture_output=True)
            
            # Config
            subprocess.run(
                ["git", "config", "user.email", "aether@aether-os.ai"],
                cwd=str(project_dir),
                capture_output=True
            )
            subprocess.run(
                ["git", "config", "user.name", "AETHER OS"],
                cwd=str(project_dir),
                capture_output=True
            )
            
            # Create README
            readme = project_dir / "README.md"
            readme.write_text(f"# {project_name}\n\nGenerated by AETHER OS\n")
            
            # Initial commit
            subprocess.run(["git", "add", "."], cwd=str(project_dir), capture_output=True)
            subprocess.run(
                ["git", "commit", "-m", "Initial commit by AETHER OS"],
                cwd=str(project_dir),
                capture_output=True
            )
            
            return {"status": "success", "message": "Repository initialized"}
        
        except Exception as e:
            return {"status": "failed", "error": str(e)}
    
    def commit_file(self, project_id: str, filename: str, message: str) -> Dict[str, Any]:
        """Hacer commit de un archivo."""
        project_dir = self.workspace_dir / project_id
        
        try:
            subprocess.run(["git", "add", filename], cwd=str(project_dir), capture_output=True)
            result = subprocess.run(
                ["git", "commit", "-m", message],
                cwd=str(project_dir),
                capture_output=True,
                text=True
            )
            
            return {"status": "success" if result.returncode == 0 else "no_changes"}
        
        except Exception as e:
            return {"status": "failed", "error": str(e)}
    
    def get_repo_status(self, project_id: str) -> Dict[str, Any]:
        """Estado del repositorio."""
        project_dir = self.workspace_dir / project_id
        
        try:
            result = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=str(project_dir),
                capture_output=True,
                text=True
            )
            
            changes = result.stdout.strip().split('\n') if result.stdout.strip() else []
            
            return {
                "status": "clean" if not changes else "dirty",
                "changes": changes
            }
        
        except Exception as e:
            return {"status": "error", "error": str(e)}
